### ISSUE TITLE
Varjocafe is not displaying any menu items

### ISSUE THREAD

**Issue by Rsl1122** [orfjackal/varjocafe#4]
Possible that Unicafe has changed their website.

![Kuva](https://i.imgur.com/oPwsRy0.png)

**Comment by orfjackal** [comment]
Fixed. It was an incompatibility between http-kit (used by VarjoCafe) and AWS's HTTPS features (used by UniCafe), which caused VarjoCafe to be unable to download the data from UniCafe.

**Comment by Rsl1122** [comment]
Thanks for the fix :)
