### ISSUE TITLE
Webserver is compromised

### ISSUE THREAD

**Issue by AuroraLS3** [orfjackal/varjocafe#5]
varjocafe.net has some Chinese symbols when accessed and the page is making a lot of requests

**Comment by luontola** [comment]
Thanks. I contacted the hosting service.

**Comment by luontola** [comment]
BTW, has VarjoCafe been working still recently? I noticed that the web site from which it retrieved the lunch menus (https://messi.hyyravintolat.fi) doesn't exist anymore. The hyyravintolat.fi domain is currently for sale.

The current https://unicafe.fi/ site seems to have been renewed and it no longer has the same lunch menu APIs, so VarjoCafe would require a major rework.

**Comment by luontola** [comment]
Looks like the domain expired on 2022-09-07. Domain renewal did not survive the sponsoring web host's migration from [Neutech](https://neutech.fi/) to [Planeetta](https://www.planeetta.fi/). 🤨 On 2022-11-11 some domain hoarder bought the domain after it was available for sale.

I would have been able to do something if somebody had reported the site not working already in September, but apparently people did not consider it important enough (there were about 80 daily users). VarjoCafe would anyways need a scraper rewrite to be compatible with Unicafe's current web site, so I'll stop maintaining this project. Anybody is free to fork it and reuse at least the frontend code.

**Comment by AuroraLS3** [comment]
Thank you for your service - it got me through uni :)

I guess https://menu.unicafe.fi/ is a decent alternative
